---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: application
    app.kubernetes.io/managed-by: helm
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 60
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- range $arg := .Values.args }}
            - "{{ tpl $arg $ }}"
            {{- end }}
          env:
            {{- range $env := .Values.environments }}
            - name: {{ $env.name }}
              value: "{{ $env.value }}"
            {{- end }}
            {{- range $secret := .Values.secrets }}
            - name: {{ $secret.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret.secretName }}
                  key: {{ $secret.secretKey }}
          {{- end }}
