---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^report/presentations
      - id: end-of-file-fixer
        exclude: ^report/presentations
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        exclude: ^report/presentations
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: remove-crlf
        exclude: ^report/presentations
      - id: remove-tabs
        exclude: ^report/presentations
        exclude_types:
          - markdown
          - gotmpl

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.2.0
    hooks:
      - id: helm-docs

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
      - id: helmlint
