apiVersion: v2
name: frontend
type: application
description: Frontend
version: 1.0.2
appVersion: "v1.0"
keywords:
  - frontend
  - react
  - nginx
maintainers:
  - name: Romanov Alexey
    email: romanowalex@mail.ru
