image:
  pullPolicy: IfNotPresent
  repository:
  tag:

port: 3000
backendServiceName:

ingress:
  enabled: true
  name:
  domain: romanow-alex.ru

environments: [ ]

secrets: [ ]

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 128Mi
