apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-configmap
    app.kubernetes.io/version: "{{ .Values.version }}"
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: todo-list
    app.kubernetes.io/managed-by: helm
data:
  datasources.yml: |-
    {{- tpl (.Files.Get "config/datasources.yml") . | nindent 4 }}

  dashboards.yml: |-
    {{- tpl (.Files.Get "config/dashboards.yml") . | nindent 4 }}

  {{- range $dashboard := .Values.dashboards }}
  {{ $dashboard }}.json: |-
    {{- printf "config/dashboards/%s.json" $dashboard | $.Files.Get | nindent 6 }}
  {{- end }}