kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-service
    app.kubernetes.io/version: "{{ .Values.version }}"
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: todo-list
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: {{ .Chart.Name }}
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}