apiVersion: v2
name: java-service
type: application
description: Helm chart for Spring Boot application with logging and tracing
version: 1.6.2
appVersion: "1.0"
home: https://github.com/Romanow/helm-charts/tree/master/charts/java-service
icon: https://raw.githubusercontent.com/Romanow/helm-charts/master/icons/spring-boot.png
sources:
  - https://spring.io/projects/spring-boot
  - https://hub.docker.com/_/amazoncorretto
keywords:
  - spring boot
  - java
  - kotlin
maintainers:
  - name: Romanov Alexey
    email: romanowalex@mail.ru
    url: https://romanow.github.io
