image:
  pullPolicy: IfNotPresent
  repository:
  tag:

ingress:
  enabled: false
  name:
  domain: romanow-alex.ru

replicas: 1
ports:
  internal: 8080
  external:

serviceName:
profile: k8s
logFolder:

database:
  name:
  host: postgres
  port: 5432
  username: program
  password: test

metrics:
  path: "/manage/prometheus"
  username: management
  password: passwd

liveness:
  delay: 60
  timeout: 10
  path: "/manage/health/readiness"
  port: 8080

readiness:
  delay: 60
  timeout: 10
  path: "/manage/health/readiness"
  port: 8080

environments: [ ]

secrets: [ ]

circuitBreaker:
  enabled: false

jaeger:
  enabled: false
  image:
    pullPolicy: IfNotPresent
    repository: jaegertracing/jaeger-agent
    tag: 1.41.0
  application:
    host: localhost
    port: 6831
  collector:
    host: jaeger-collector
    port: 14250
  ports:
    compactThrift: 6831
    binaryThrift: 6832
    admin: 14271
  resources:
    requests:
      cpu: 500m
      memory: 1024Mi
    limits:
      cpu: 500m
      memory: 1024Mi

filebeat:
  enabled: false
  image:
    pullPolicy: IfNotPresent
    repository: docker.elastic.co/beats/filebeat
    tag: 7.15.0
  logstash:
    host: logstash
    port: 5044
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 50m
      memory: 128Mi

resources:
  requests:
    cpu: 500m
    memory: 1024Mi
  limits:
    cpu: 500m
    memory: 1024Mi
