# -- Image name and version
image:
  pullPolicy: IfNotPresent
  repository: logstash
  tag: 7.17.8

# -- Logstash port
port: 5044

# -- Custom service name
# @default -- .Release.Name
serviceName:

elasticsearch:
  # -- Elastic address
  url: http://elasticsearch:9200
  # -- Elastic username (optional)
  username: logging
  # -- Elastic password (optional)
  password: qwerty

resources:
  # -- Requested resources
  requests:
    cpu: 500m
    memory: 1024Mi
  # -- Limited resources
  limits:
    cpu: 500m
    memory: 1024Mi
