# -- Image name and version
image:
  pullPolicy: IfNotPresent
  repository: logstash
  tag: 7.17.8

# -- Logstash ports
ports:
  beats: 5044
  http: 9600

# -- Custom service name
# @default -- .Release.Name
serviceName:

outputs:
  console:
    # -- Enable console output
    enabled: false
  elasticsearch:
    # -- Enable ElasticSearch output
    enabled: false
    # -- Elastic address
    url: http://elasticsearch:9200
    # -- Elastic username (optional)
    username: logging
    # -- Elastic password (optional)
    password: qwerty

resources:
  # -- Requested resources
  requests:
    cpu: 500m
    memory: 1536Mi
  # -- Limited resources
  limits:
    cpu: 500m
    memory: 1536Mi
