# -- Image name and version
image:
  pullPolicy: IfNotPresent
  repository: jaegertracing/jaeger
  tag: 2.9.0

# -- Custom service name
# @default -- .Release.Name
serviceName:

# -- Jaeger ports
ports:
  http: 16686
  telemetry: 4318
  metrics: 8888

ingress:
  # -- Enable ingress
  enabled: true
  # -- Ingress name
  name: jaeger
  # -- Domain
  domain: romanow-alex.ru

metrics:
  enabled: true
  storage:
    type: elasticsearch
    elasticsearch:
      # -- Elastic username (optional)
      username: logging
      # -- Elastic password (optional)
      password: qwerty
      # -- Elastic address
      server_urls:
        - http://elasticsearch:9200

traces:
  storage:
    type: elasticsearch
    elasticsearch:
      # -- Elastic username (optional)
      username: logging
      # -- Elastic password (optional)
      password: qwerty
      # -- Elastic address
      server_urls:
        - http://elasticsearch:9200
    memory:
      max_traces: 30000

resources:
  # -- Requested resources
  requests:
    cpu: 300m
    memory: 1024Mi
  # -- Limited resources
  limits:
    cpu: 300m
    memory: 1024Mi
