# -- Image name and version
image:
  pullPolicy: IfNotPresent
  repository: jaegertracing/all-in-one
  tag: 1.57.0

# -- Custom service name
# @default -- .Release.Name
serviceName:

# -- Jaeger ports
ports:
  http: 16686
  otlp: 4318

ingress:
  # -- Enable ingress
  enabled: true
  # -- Ingress name
  name: jaeger
  # -- Domain
  domain: romanow-alex.ru

storage:
  type: elasticsearch
  elasticsearch:
    # -- Elastic address
    url: http://elasticsearch:9200
    # -- Elastic username (optional)
    username: logging
    # -- Elastic password (optional)
    password: qwerty

resources:
  # -- Requested resources
  requests:
    cpu: 300m
    memory: 1024Mi
  # -- Limited resources
  limits:
    cpu: 300m
    memory: 1024Mi
