image:
  pullPolicy: IfNotPresent
  repository: prom/prometheus
  tag: v2.40.0

ports:
  internal: 9090
  external:

serviceName:

resources:
  requests:
    cpu: 300m
    memory: 1024Mi
  limits:
    cpu: 300m
    memory: 1024Mi
