apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName | default .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    app: {{ .Release.Name }}
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.ports.internal }}
      targetPort: {{ .Chart.Name }}
      nodePort: {{ .Values.ports.external }}
