apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pipeline
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: logging
    app.kubernetes.io/managed-by: helm
data:
  pipeline.conf: |-
    input {
      beats {
        port => {{ .Values.port }}
      }
    }
    output {
      elasticsearch {
        hosts => "{{ .Values.elasticsearch.url }}"
    {{- if .Values.elasticsearch.username }}
        user => "{{ .Values.elasticsearch.username }}"
    {{- end }}
    {{- if .Values.elasticsearch.password }}
        password => "{{ .Values.elasticsearch.password }}"
    {{- end }}
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: logging
    app.kubernetes.io/managed-by: helm
data:
  logstash.yml: |-
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
