apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: logging
    app.kubernetes.io/managed-by: helm
data:
  logstash.yml: |-
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |-
    input {
      beats {
        port => {{ .Values.ports.beats }}
      }
    }
    output {
    {{- if .Values.outputs.console.enabled }}
      stdout { }
    {{- end }}
    {{- if .Values.outputs.elasticsearch.enabled }}
      elasticsearch {
        hosts => "{{ .Values.outputs.elasticsearch.url }}"
    {{- if .Values.outputs.elasticsearch.username }}
        user => "{{ .Values.outputs.elasticsearch.username }}"
    {{- end }}
    {{- if .Values.outputs.elasticsearch.password }}
        password => "{{ .Values.outputs.elasticsearch.password }}"
    {{- end }}
      }
    {{- end }}
    }
