kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.serviceName | default .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: logging
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.ports.beats }}
      targetPort: beats
