apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-cluster-role
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-cluster-role
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
rules:
  - apiGroups: [ "" ]
    resources:
      - nodes
      - nodes/proxy
      - nodes/metrics
      - services
      - endpoints
      - pods
    verbs: [ "get", "list", "watch" ]
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
    resources:
      - ingresses/status
      - ingresses
    verbs: [ "get", "list", "watch" ]
  - nonResourceURLs: [ "/metrics" ]
    verbs: [ "get" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-cluster-role-binding
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-cluster-role-binding
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Chart.Name }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ .Chart.Name }}-service-account
    namespace: {{ .Values.global.namespace }}