apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-configmap
    app.kubernetes.io/version: "{{ .Values.version }}"
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
data:
  prometheus.yml: |-
  {{- .Files.Get "config/prometheus.yml" | nindent 4 }}