apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/managed-by: helm
data:
  prometheus.yml: |-
  {{- .Files.Get "config/prometheus.yml" | nindent 4 }}
