apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{ .Values.version }}"
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: micro-services
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/version: "{{ .Values.version }}"
        app.kubernetes.io/component: monitoring
        app.kubernetes.io/part-of: micro-services
        app.kubernetes.io/managed-by: helm
    spec:
      serviceAccountName: {{ .Chart.Name }}-service-account
      containers:
        - name: {{ .Chart.Name }}
          image: "prom/prometheus:{{ .Values.version }}"
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
          args:
            - "--storage.tsdb.retention.time=12h"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - name: {{ .Chart.Name }}
              containerPort: {{ .Values.port }}
          volumeMounts:
            - name: {{ .Chart.Name }}-config-volume
              mountPath: /etc/prometheus/
            - name: {{ .Chart.Name }}-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: {{ .Chart.Name }}-storage-volume
        - name: {{ .Chart.Name }}-config-volume
          configMap:
            defaultMode: 420
            name: {{ .Chart.Name }}-configmap