apiVersion: v2
name: influxdb
type: application
description: The Time Series Data Platform where developers build IoT, analytics, and cloud applications.
version: 1.3.2
appVersion: "1.8.4"
home: https://github.com/Romanow/helm-charts/tree/master/charts/influxdb
icon: https://raw.githubusercontent.com/Romanow/helm-charts/master/icons/influxdb.png
sources:
  - https://www.influxdata.com/
  - https://hub.docker.com/_/influxdb
keywords:
  - influxdb
  - database
maintainers:
  - name: Romanov Alexey
    email: romanowalex@mail.ru
    url: https://romanow.github.io
