image:
  pullPolicy: IfNotPresent
  repository: influxdb
  tag: 1.8.4

serviceName:
ports:
  internal: 8086
  external:

database: k6

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 200m
    memory: 512Mi
