apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: logging
    app.kubernetes.io/managed-by: helm
data:
  config.yml: |-
    service:
      extensions: [jaeger_storage, jaeger_query]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger_storage_exporter]

    extensions:
      jaeger_query:
        storage:
          traces: storage
          {{- if .Values.metrics.enabled }}
          metrics: storage
          {{- end }}
      jaeger_storage:
        backends:
          storage:
            {{ include "storageConfig" .Values.traces.storage }}
        {{- if .Values.metrics.enabled }}
        metric_backends:
          storage:
            {{ include "storageConfig" .Values.metrics.storage }}
        {{- end }}
    receivers:
      otlp:
        protocols:
          grpc:
          http:
            endpoint: "0.0.0.0:4318"

    processors:
      batch:

    exporters:
      jaeger_storage_exporter:
        trace_storage: storage
