apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: tracing
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: admin
      protocol: TCP
      port: {{ .Values.ports.admin }}
      targetPort: admin
    - name: otlp
      protocol: TCP
      port: {{ .Values.ports.otlp }}
      targetPort: otlp
    - name: zipkin
      protocol: TCP
      port: {{ .Values.ports.zipkin }}
      targetPort: zipkin
