apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    url: http://{{ .Values.prometheusService }}:9090
    access: proxy
    version: 1
    editable: true

  - name: InfluxDB
    type: influxdb
    url: http://{{ .Values.influxService }}:8086
    database: k6
    access: proxy
    editable: true
    jsonData:
      httpMode: GET
    version: 1
