apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName | default (printf "%s-collector" .Release.Name) }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: tracing
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    app: {{ .Release.Name }}-collector
  ports:
    - name: grpc
      protocol: TCP
      port: {{ .Values.ports.grpc }}
      targetPort: grpc
    - name: http
      protocol: TCP
      port: {{ .Values.ports.http }}
      targetPort: http
    - name: admin
      protocol: TCP
      port: {{ .Values.ports.admin }}
      targetPort: admin
