apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: logging
    app.kubernetes.io/managed-by: helm
data:
  fluent-bit.conf: |-
    [SERVICE]
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_PORT    2020
        Health_Check On

    [INPUT]
        Name    tcp
        Listen  0.0.0.0
        Port    {{ .Values.port }}
        Format  json

    [OUTPUT]
        Name    es
        Host    {{ .Values.elasticsearch.host }}
        Port    {{ .Values.elasticsearch.port }}
        Index   {{ .Values.elasticsearch.index }}
        Match   *
        Suppress_Type_Name On
    {{ if .Values.debug }}
    [OUTPUT]
        Name    stdout
        Match   *
    {{- end }}
