apiVersion: v2
name: jaeger-collector
type: application
description: Jaeger tracing collector
version: 1.0.0
appVersion: "1.41.0"
keywords:
  - jaeger
  - jaeger-collector
  - tracing
maintainers:
  - name: Romanov Alexey
    email: romanowalex@mail.ru
