# -- Image name and version
image:
  pullPolicy: IfNotPresent
  repository: jaegertracing/jaeger-collector
  tag: 1.41.0

# -- Custom service name
# @default -- .Release.Name
serviceName:

# -- Jaeger collector ports
ports:
  grpc: 14250
  http: 14268
  admin: 14269

elasticsearch:
  # -- Elastic address
  url: http://elasticsearch:9200
  # -- Elastic username (optional)
  username: logging
  # -- Elastic password (optional)
  password: qwerty

resources:
  # -- Requested resources
  requests:
    cpu: 300m
    memory: 1024Mi
  # -- Limited resources
  limits:
    cpu: 300m
    memory: 1024Mi
