apiVersion: v2
name: postgres
type: application
description: PostgreSQL is a powerful, open source object-relational database system.
version: 1.1.2
home: https://github.com/Romanow/helm-charts/tree/master/charts/postgres
icon: https://github.com/Romanow/helm-charts/tree/master/images/postgres.png
appVersion: "15"
sources:
  - https://www.postgresql.org/
  - https://hub.docker.com/_/postgres
keywords:
  - postgres
  - database
maintainers:
  - name: Romanov Alexey
    email: romanowalex@mail.ru
    url: https://romanow.github.io
