image:
  pullPolicy: IfNotPresent
  repository: postgres
  tag: 15

ports:
  internal: 5432
  external:

serviceName:

defaultDatabase:
  name: postgres
  user: postgres
  password: postgres

users:
  - name: program
    password: test

databases:
  - name: services
    user: program

config:
  params: {}

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 100m
    memory: 512Mi
