image:
  pullPolicy: IfNotPresent
  repository: postgres
  tag: 15

ports:
  internal: 5432
  external:

serviceName:

defaultDatabase:
  name: postgres
  user: postgres
  password: postgres

users:
  - name: program
    password: test

databases:
  - name: services
    user: program

#configs: [ ]
configs:
  - name: postgres.conf
    file: config/postgres.conf
    path: /var/lib/postgresql/data/postgres.conf

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 512Mi
