apiVersion: v2
name: node-exporter
type: application
description: Prometheus exporter for hardware and OS metrics exposed by *NIX kernels, written in Go with pluggable metric collectors.
version: 1.1.1
appVersion: "1.5.0"
icon: https://www.vectorlogo.zone/util/preview.html?image=/logos/prometheusio/prometheusio-icon.svg
sources:
  - https://github.com/Romanow/helm-charts/tree/master/charts/node-exporter
  - https://github.com/prometheus/node_exporter
keywords:
  - node-exporter
  - prometheus
  - monitoring
maintainers:
  - name: Romanov Alexey
    email: romanowalex@mail.ru
    url: https://romanow.github.io
