image:
  pullPolicy: IfNotPresent
  repository: prom/node-exporter
  tag: v1.5.0

ports:
  internal: 9100
  external:

serviceName:

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 200m
    memory: 512Mi
