image:
  pullPolicy: IfNotPresent
  repository: prom/node-exporter
  tag: v1.5.0

port: 9100
serviceName:

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 200m
    memory: 512Mi
