name: "Release Charts"
on:
  push:
    branches:
      - master
#    paths:
#      - 'charts/**'
#      - '!charts/**/README.md'
#      - '!charts/**/README.md.gotmpl'

jobs:
  validate:
    name: Validate charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v3

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Install helm-docs
        run: |
          cd /tmp
          wget https://github.com/norwoodj/helm-docs/releases/download/v${{env.HELM_DOCS_VERSION}}/helm-docs_${{env.HELM_DOCS_VERSION}}_Linux_x86_64.tar.gz
          tar -xvf helm-docs_${{env.HELM_DOCS_VERSION}}_Linux_x86_64.tar.gz
          sudo mv helm-docs /usr/local/sbin
        env:
          HELM_DOCS_VERSION: "1.11.0"

      - name: Validate
        uses: pre-commit/action@v3.0.0

  test:
    name: Test charts
    runs-on: ubuntu-latest
    needs: validate
    outputs:
      output1: ${{ steps.changes.outputs.changed }}
      output2: ${{ steps.changes.outputs.changed_charts }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Install chart linting
        uses: helm/chart-testing-action@v2.3.1

      - name: List changed charts
        id: changes
        run: |
          changed=$(ct list-changed --config .ct.yaml)
          charts=$(echo "$changed" | tr '\n' ' ' | xargs)
          echo "$changed >> $charts"
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "changed_charts=$charts" >> $GITHUB_OUTPUT
          fi

      - name: Create kind cluster
        if: ${{ success() && steps.changes.outputs.changed == 'true' }}
        uses: helm/kind-action@v1.4.0

      - name: Run ct install
        if: ${{ success() && steps.changes.outputs.changed == 'true' }}
        run: ct lint-and-install --config=.ct.yaml --excluded-charts=java-service,frontend

  release:
    name: Publish charts
    runs-on: ubuntu-latest
    needs: test
    if: needs.test.outputs.changed == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true
