name: "Release Charts"
on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'
      - '!charts/**/README.md'
      - '!charts/**/README.md.gotmpl'

jobs:
  validate:
    name: Validate charts
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.changes.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v3

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Install helm-docs
        run: |
          wget https://github.com/norwoodj/helm-docs/releases/download/v1.11.0/helm-docs_1.11.0_Linux_x86_64.tar.gz -O /tmp/helm-docs.tar.gz
          tar -xvf /tmp/helm-docs.tar.gz -C /tmp
          sudo mv /tmp/helm-docs /usr/local/sbin

      - name: Validate
        uses: pre-commit/action@v3.0.0

      - name: Detect charts changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          working-directory: charts
          filters: |
            charts:
              - '**'

      - name: Log
        run: |
          echo ${{ steps.changes.outputs.packages }}

  test:
    name: Test charts
    runs-on: ubuntu-latest
    needs: validate
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Install chart linting
        uses: helm/chart-testing-action@v2.3.1

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0

      - name: Run ct install
        run: ct lint-and-install --config=.ct.yaml --charts charts/${{ matrix.package }}

  release:
    name: Publish charts
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true
