name: "Release Charts"
on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'
      - '!charts/**/README.md'
      - '!charts/**/README.md.gotmpl'

jobs:
  validate:
    name: Validate charts
    runs-on: ubuntu-latest
    outputs:
      matrix: |
        {
          "chart": "${{ steps.set-matrix.outputs.matrix }}"
        }
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v3

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Install helm-docs
        run: |
          wget https://github.com/norwoodj/helm-docs/releases/download/v1.11.0/helm-docs_1.11.0_Linux_x86_64.tar.gz -O /tmp/helm-docs.tar.gz
          tar -xvf /tmp/helm-docs.tar.gz -C /tmp
          sudo mv /tmp/helm-docs /usr/local/sbin

      - name: Validate
        uses: pre-commit/action@v3.0.0

      - name: Get changed files
        id: detect-changes
        uses: tj-actions/changed-files@v35
        with:
          dir_names: true
          dir_names_max_depth: 2
          files: |
            charts/**

      - name: Configure matrix for test
        id: set-matrix
        run: |
          EXCLUDED=$(cat .ct.yaml | yq '.excluded-charts[] |= "charts/" + .' | yq -o json '.excluded-charts // []')
          CHARTS="${{ steps.detect-changes.outputs.all_changed_files }}"
          CHARTS_JSON=$(echo "${CHARTS}" | jq -R -s -c 'split("\n")[:-1]')
          OUTPUT_JSON=$(echo "{\"excluded\": ${EXCLUDED}, \"all\": ${CHARTS_JSON}}" | jq -c '.all-.excluded')
          echo "charts=${OUTPUT_JSON}" >> "$GITHUB_OUTPUT"

  test:
    name: Test charts
    runs-on: ubuntu-latest
    needs: validate
    strategy:
      matrix: ${{ fromJSON(needs.validate.outputs.matrix) }}
      max-parallel: 10
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Install chart linting
        uses: helm/chart-testing-action@v2.3.1

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0

      - name: Run ct install
        run: ct lint-and-install --config=.ct.yaml --charts ${{ matrix.chart }}

  release:
    name: Publish charts
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true
